// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Vertical.Product.Service.Data;

namespace Vertical.Product.Service.Data
{
    public partial class AdventureWorksLT2019Context
    {

        [DbFunction("ufnGetAllCategories", "dbo")]
        public IQueryable<ufnGetAllCategoriesResult> ufnGetAllCategories()
        {
            return FromExpression(() => ufnGetAllCategories());
        }

        [DbFunction("ufnGetCustomerInformation", "dbo")]
        public IQueryable<ufnGetCustomerInformationResult> ufnGetCustomerInformation(int? CustomerID)
        {
            return FromExpression(() => ufnGetCustomerInformation(CustomerID));
        }

        [DbFunction("ufnGetSalesOrderStatusText", "dbo")]
        public static string ufnGetSalesOrderStatusText(byte? Status)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ufnGetAllCategoriesResult>().HasNoKey();
            modelBuilder.Entity<ufnGetCustomerInformationResult>().HasNoKey();
        }
    }
}
